#!/bin/bash

yazi_="$(which yazi)"
function yazi() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	$yazi_ "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}
