#!/bin/bash

touch /tmp/wsl-xclip-debug
debug() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] [PID: $$] $1" >>/tmp/wsl-xclip-debug
}
debug ""

clip=$(type -ap xclip | grep -v "$0" | head -n 1)
debug "clip: $clip"

if [[ "$*" == *"-i"* ]] || [[ "$*" == *"-in"* ]]; then
  # debug "copy"
  # input=$(cat)
  # debug "copied: $input"
  # debug "@: $*"
  # # echo -n "$input" | "$clip" ${*//-quiet/}
  # echo "$input" | "$clip" "$@"
  # # (echo -n "$input" | "$clip" "$@" >/dev/null 2>&1) &
  # debug "xclip"
  # # echo -n "$input" | clip.exe
  # # debug "clip.exe"
  # # printf "%s" "$input" | tee >("$clip" "$@") | clip.exe
  # # debug "tee"
  coproc xclip_proc { "$clip" "$@"; }
  while IFS= read -r line; do
    debug "line: $line"
    echo "$line" | clip.exe
    debug "clip.exe"
    echo "$line" >&"${xclip_proc[1]}"
    debug "xclip"
  done
  debug "copy done"
else
  debug "paste"
  debug "@: $*"
  "$clip" "$@"
  debug "paste done"
fi
